### ISSUE TITLE
Add product image to `/views/thank-you.html` and make it responsive

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-signup#91]
The following image needs to be replaced with the proper product image

![image](https://cloud.githubusercontent.com/assets/675909/12864630/aa514f8c-cc88-11e5-827a-6df34ded6ade.png)

... so that it looks like this

![image](https://cloud.githubusercontent.com/assets/675909/12864631/c8de7f42-cc88-11e5-8efd-16f1e035178c.png)

Additionally, the image needs to be responsive so that it is larger when viewed on tablets

# TODO

- [x] Replace the placeholder image with the proper image
- [x] Ensure that the image service is used
- [x] Make image responsive

**Comment by lc512k** [comment]
https://github.com/Financial-Times/next-signup/pull/124
